---
- name: Install git
  apt:
    name: git
    state: latest
  become: yes
  tags: github

- name: Install/Update root gitconfig
  template:
    src: gitconfig.j2
    dest: /root/.gitconfig
    owner: root
    group: root
    mode: '0644'
  become: yes
  tags: github

- name: Ensure root SSH folder exists
  file:
    path: /root/.ssh
    owner: root
    group: root
    mode: '0700'
    state: directory
  become: yes
  tags: github

- name: Add root private SSH keys
  copy:
    dest: '/root/.ssh/id_{{ github_ssh_privkey_type }}'
    owner: root
    group: root
    mode: '0600'
    content: '{{ github_ssh_privkey }}'
  become: yes
  tags: github

- name: Pull list of SSH fingerprints from GitHub
  command: ssh-keyscan -H github.com
  register: github_keyscan
  tags: github

- name: Add GitHub's SSH fingerprints to known_hosts
  lineinfile:
    path: /root/.ssh/known_hosts
    line: '{{ item }}'
    create: yes
  become: yes
  with_items: '{{ github_keyscan.stdout_lines }}'
  tags: github