---
- name: Configure dhcpcd
  template:
    src: dhcpcd.conf.j2
    dest: /etc/dhcpcd.conf
    owner: root
    group: netdev
    mode: '0644'
  tags:
    - common
    - network

- name: Restart dhcpcd service
  systemd:
    name: dhcpcd
    state: restarted
    daemon_reload: yes
  tags:
    - common
    - network