---
- name: Add SSH keys to authorized_keys
  authorized_key:
    user: pi
    key: '{{ item }}'
    state: present
  with_items: '{{ ssh_pubkeys }}'
  tags: [common, ssh]

- import_tasks: raspi_config.yml
  tags: common

- name: Update default 'pi' user password
  user:
    name: pi
    password: '{{ raspi_user_password }}'
  when: raspi_user_password | length
  tags: [common, passwd]

- import_tasks: dhcpcd.yml
  tags: common

- name: Perform full system update
  apt:
    upgrade: full
    update_cache: yes
  tags: [common, update]

- name: Enable automatic updates
  apt:
    name: unattended-upgrades
    state: latest
  tags: common

- name: Install additional software
  apt:
    name: [vim, git]
    state: latest
  tags: common

- import_tasks: log2ram.yml
  tags: common

- name: Reboot system to apply all changes/updates
  reboot:
  tags: common

- name: Remove packages that are no longer needed
  apt:
    autoremove: yes
    autoclean: yes
  tags: [common, cleanup]
