---
- import_tasks: raspi_config.yml
  tags:
    - common
    - raspi

- name: Install/Update dhcpcd configuration
  template:
    src: dhcpcd.conf.j2
    dest: /etc/dhcpcd.conf
    owner: root
    group: netdev
    mode: '0644'
  become: yes
  register: dhcpcd_config
  tags:
    - common
    - network

- name: Restart dhcpcd to load new configuration changes
  systemd:
    name: dhcpcd
    state: restarted
    daemon_reload: yes
  become: yes
  when: dhcpcd_config.changed
  tags:
    - common
    - network

- name: Add SSH keys to pi user
  authorized_key:
    user: pi
    key: '{{ item }}'
    state: present
  with_items: '{{ raspi_ssh_pubkeys }}'
  tags:
    - common
    - ssh

- name: Set pi user password
  user:
    name: pi
    password: '{{ raspi_user_password }}'
  become: yes
  when: raspi_user_password | length
  tags:
    - common
    - passwd

- name: Mount additional network shares
  mount:
    path: '{{ item.path }}'
    src: '{{ item.src }}'
    fstype: '{{ item.fstype }}'
    opts: '{{ item.opts }}'
    state: mounted
  become: yes
  with_items: '{{ raspi_network_mounts }}'
  tags:
    - common
    - mounts

- import_tasks: log2ram.yml
  tags:
    - common
    - log2ram

- name: Enable automatic updates
  apt:
    name: unattended-upgrades
    state: latest
  become: yes
  tags:
    - common
    - updates

- name: Perform full system update
  apt:
    upgrade: full
    update_cache: yes
  become: yes
  register: apt_update
  tags:
    - common
    - updates

- name: Restart system to fully apply all updates
  reboot:
    reboot_timeout: 3600
  become: yes
  when: apt_update.changed
  tags:
    - common
    - updates

- name: Remove packages that are no longer needed
  apt:
    autoremove: yes
    autoclean: yes
  become: yes
  tags:
    - common
    - cleanup
