---
## Pi-Hole settings
# Passwords are double hashed using SHA256 - copy from an existing setupVars.conf
pihole_password: ''
pihole_admin_email: admin@example.com

# Forwarding DNS servers
# 2 IPv4, 2 IPv6 max
pihole_dns:
  - 1.1.1.1#53
  - 1.0.0.1#53
  - 2606:4700:4700::1111#53
  - 2606:4700:4700::1001#53

# Allow DNS queries from all or a specific interfaces
pihole_dnsmasq_mode: single

# General security settings
pihole_bogus_priv: yes
pihole_fqdn_required: yes
pihole_dnssec: yes

# Conditional forwarding for local hostname resolution
pihole_conditional_forwarding: no
pihole_conditional_forwarding_ip: 192.168.1.1
pihole_conditional_forwarding_domain: home.lan

# Generally can be left as default
pihole_api_exclude_domains: []
pihole_api_exclude_clients: []
pihole_api_query_log: all
pihole_api_privacy_mode: no

# Clear old Pi-Hole query logs
pihole_flush_logs: no

## Unbound settings
# Enabling unbound will automatically force Pi-Hole to use it
pihole_enable_unbound: no
unbound_root_hints: /var/lib/unbound/root.hints
unbound_port: 5353

## Sync settings
pihole_enable_sync: no

# Git options
git_name: root
git_email: root@example.com
git_username: root

# Private key will needed for passwordless syncing, private repo's, and pushing changes
pihole_sync_ssh_key: |
  -----BEGIN RSA PRIVATE KEY-----
  ...
  -----END RSA PRIVATE KEY-----
pihole_sync_repo: https://github.com/stevejenkins/my-pihole-lists

# Include syncing /etc/hosts
pihole_sync_enable_hosts: yes

# Minutes between syncing
pihole_sync_rate: 15

# "Leaders" will push updates instead of pull
pihole_sync_leader: no
