---
- name: Ensure Pi-Hole directory exists
  file:
    path: /etc/pihole
    # owner and group handled by Pi-Hole
    mode: '0755'
    state: directory
  tags: pihole

- name: Install Pi-Hole configuration file
  template:
    src: setupVars.conf.j2
    dest: /etc/pihole/setupVars.conf
    # owner and group handled by Pi-Hole
    mode: '0644'
  tags: pihole

- name: Download Pi-Hole installer
  get_url:
    url: https://install.pi-hole.net
    dest: /tmp/pihole-installer.sh
  tags: pihole

- name: Run Pi-Hole installer
  command: bash /tmp/pihole-installer.sh --unattended
  tags: pihole

- name: Cleanup Pi-Hole installer
  file:
    path: /tmp/pihole-installer.sh
    state: absent
  tags: [pihole, cleanup]

- name: Make system use Pi-Hole for DNS
  lineinfile:
    path: /etc/dhcpcd.conf
    regexp: '^(\s*)static domain_name_servers='
    line: '\1static domain_name_servers=127.0.0.1 ::1'
    backrefs: yes
  tags: [pihole, network]

- name: Restart dhcpcd service
  systemd:
    name: dhcpcd
    state: restarted
    daemon_reload: yes
  tags: [pihole, network]

- import_tasks: pihole_sync.yml
  when: pihole_enable_sync | bool
  tags: pihole

- import_tasks: unbound.yml
  when: pihole_enable_unbound | bool
  tags:
  - pihole

- name: Flush Pi-Hole logs
  command: pihole -f
  when: pihole_flush_logs | bool
  tags: [pihole, cleanup]