---
- name: Ensure Pi-Hole directory exists
  file:
    path: /etc/pihole
    # owner and group handled by Pi-Hole
    mode: '0755'
    state: directory
  become: yes
  tags: pihole

- name: Install/Update Pi-Hole configuration
  template:
    src: setupVars.conf.j2
    dest: /etc/pihole/setupVars.conf
    # owner and group handled by Pi-Hole
    mode: '0644'
  become: yes
  tags: pihole

- name: Download Pi-Hole installer
  get_url:
    url: https://install.pi-hole.net
    dest: /tmp/pihole-installer.sh
    force: yes
  tags: pihole

- name: Run Pi-Hole installer
  command: bash /tmp/pihole-installer.sh --unattended
  become: yes
  tags: pihole

- name: Cleanup Pi-Hole installer
  file:
    path: /tmp/pihole-installer.sh
    state: absent
  tags:
    - pihole
    - cleanup

- name: Ensure system is using Pi-Hole (self) for DNS
  lineinfile:
    path: /etc/dhcpcd.conf
    regexp: '^(\s*)static domain_name_servers='
    line: '\1static domain_name_servers=127.0.0.1 ::1'
    backrefs: yes
  become: yes
  register: pihole_dhcpcd_config
  tags:
    - pihole
    - network

- name: Restart dhcpcd to load new configuration changes
  systemd:
    name: dhcpcd
    state: restarted
    daemon_reload: yes
  become: yes
  when: pihole_dhcpcd_config.changed
  tags:
    - pihole
    - network

- name: Setup cronjob for daily adlist updates
  cron:
    name: Daily Pi-Hole adlist update
    cron_file: pihole-daily
    job: /usr/local/bin/pihole updateGravity >/var/log/pihole_updateGravity.log || cat /var/log/pihole_updateGravity.log
    hour: '{{ pihole_cron_hour | quote }}'
    minute: '{{ pihole_cron_minute | quote }}'
    user: root
    state: present
  become: yes
  tags:
    - pihole
    - cron

- name: Setup Pi-Hole list syncing
  include_tasks: sync.yml
  when: pihole_sync
  tags:
    - pihole
    - sync

- name: Flush old Pi-Hole query logs
  command: /usr/local/bin/pihole -f
  become: yes
  when: pihole_flush_logs
  tags:
    - pihole
    - cleanup