---
- import_tasks: git_ssh.yml
  tags:
    - sync

- name: Download personal list repo
  git:
    repo: '{{ pihole_sync_repo }}'
    dest: '{{ pihole_sync_repo_dir }}'
    update: yes
  tags:
    - sync

- name: Download pihole-cloudsync
  git:
    repo: git@github.com:stevejenkins/pihole-cloudsync.git
    dest: /opt/pihole-cloudsync
    update: yes
  tags:
    - sync

- name: Copy pihole-cloudsync locally
  copy:
    src: /opt/pihole-cloudsync/pihole-cloudsync
    dest: /usr/local/bin/pihole-cloudsync
    owner: root
    group: root
    mode: '0755'
    remote_src: yes
  tags:
    - sync

- name: Update local pihole-cloudsync script variables
  lineinfile:
    path: /usr/local/bin/pihole-cloudsync
    regexp: '^#?{{ item.var }}='
    line: '{{ item.var }}={{ item.val }}'
  with_items:
    - {var: personal_git_dir, val: '{{ pihole_sync_repo_dir }}'}
    - {var: enable_hosts, val: '{{ pihole_sync_enable_hosts }}'}
  tags:
    - sync

- name: Update hosts file to work with pihole-cloudsync
  lineinfile:
    path: /etc/hosts
    line: '{{ item }}'
  with_items:
    - '# SHARED HOSTS - START'
    - '# SHARED HOSTS - END'
  when: pihole_sync_enable_hosts | bool
  tags:
    - sync

- name: Perform inital sync
  command: /usr/local/bin/pihole-cloudsync --initpull
  tags:
    - sync

- name: Setup crontab for periodically pulling new changes
  cron:
    name: pihole-cloudsync
    minute: '*/{{ pihole_sync_rate }}'
    job: /usr/local/bin/pihole-cloudsync --pull 2>&1 > /dev/null
  when: pihole_sync_leader | bool == False
  tags:
    - sync

- name: Setup crontab for periodically pushing new changes
  cron:
    name: pihole-cloudsync
    minute: '*/{{ pihole_sync_rate }}'
    job: /usr/local/bin/pihole-cloudsync --push 2>&1 > /dev/null
  when: pihole_sync_leader | bool
  tags:
    - sync