---
- name: Pull sync repo
  git:
    repo: '{{ pihole_sync_repo }}'
    dest: '/opt/{{ pihole_sync_repo | basename | replace(".git", "") }}'
    update: yes
  become: yes
  tags: sync

- name: Pull pihole-cloudsync from GitHub
  git:
    repo: git@github.com:stevejenkins/pihole-cloudsync.git
    dest: /opt/pihole-cloudsync
    update: yes
  become: yes
  tags: sync

- name: Copy pihole-cloudsync to /usr/local/bin
  copy:
    src: /opt/pihole-cloudsync/pihole-cloudsync
    dest: /usr/local/bin/pihole-cloudsync
    owner: root
    group: root
    mode: '0755'
    remote_src: yes
  become: yes
  tags: sync

- name: Update pihole-cloudsync script variables
  lineinfile:
    path: /usr/local/bin/pihole-cloudsync
    regexp: '^#?{{ item.var }}='
    line: '{{ item.var }}={{ item.val }}'
    state: present
  become: yes
  with_items:
    - { var: personal_git_dir, val: '/opt/{{ pihole_sync_repo | basename | replace(".git", "") }}' }
    - { var: enable_hosts, val: '{{ pihole_sync_hosts }}' }
  tags: sync

- name: Make sure hosts file is updated to support pihole-cloudsync
  lineinfile:
    path: /etc/hosts
    line: '{{ item }}'
    state: present
  become: yes
  with_items:
    - '# SHARED HOSTS - START'
    - '# SHARED HOSTS - END'
  when: pihole_sync_hosts
  tags: sync

- name: Perform inital sync
  command: /usr/local/bin/pihole-cloudsync --initpull
  become: yes
  tags: sync

- name: Setup cron for periodic pulling of new changes
  cron:
    name: pihole-cloudsync pull
    minute: '*/{{ pihole_sync_rate }}'
    job: /usr/local/bin/pihole-cloudsync --pull 2>&1 > /dev/null
    state: present
  become: yes
  when: not pihole_sync_leader
  tags: sync

- name: Setup cron for periodic pushing of new changes
  cron:
    name: pihole-cloudsync push
    minute: '*/{{ pihole_sync_rate }}'
    job: /usr/local/bin/pihole-cloudsync --push 2>&1 > /dev/null
    state: present
  become: yes
  when: pihole_sync_leader
  tags: sync