---
- name: Install unbound
  apt:
    name: unbound
    state: latest
  tags: unbound

- name: Download latest root nameservers
  get_url:
    url: '{{ unbound_root_hints_url }}'
    dest: '{{ unbound_root_hints }}'
    owner: root
    group: root
    mode: '0644'
  tags: unbound

- name: Enable periodic root nameserver updates
  cron:
    name: Bi-yearly update root nameservers
    minute: '0'
    hour: '0'
    day: '1'
    month: '*/6'
    job: 'curl {{ unbound_root_hints_url | quote }} -o {{ unbound_root_hints | quote }}.new && mv {{ unbound_root_hints | quote }}.new {{ unbound_root_hints | quote }}'
  tags: unbound

- name: Install/Update unbound configuration
  template:
    src: unbound.conf.j2
    dest: /etc/unbound/unbound.conf.d/pi-hole.conf
    owner: root
    group: root
    mode: '0644'
  register: unbound_config
  tags: unbound

- name: Restart unbound to load new configuration changes
  systemd:
    name: unbound
    state: restarted
    daemon_reload: yes
  when: unbound_config.changed
  tags: unbound

- name: Ensure unbound service is enabled and running
  systemd:
    name: unbound
    state: started
    enabled: yes
  tags: unbound

- name: Remove existing Pi-Hole DNS settings
  lineinfile:
    path: /etc/pihole/setupVars.conf
    regexp: '^PIHOLE_DNS_'
    state: absent
  tags: unbound

- name: Set Pi-Hole DNS to use local unbound instance
  lineinfile:
    path: /etc/pihole/setupVars.conf
    state: present
    line: '{{ item }}'
  with_items:
    - 'PIHOLE_DNS_1=127.0.0.1#{{ unbound_port }}'
    - 'PIHOLE_DNS_2=::1#{{ unbound_port }}'
  tags: unbound

- name: Reconfigure Pi-Hole to apply new settings
  command:
    argv:
      - /etc/.pihole/automated install/basic-install.sh
      - --reconfigure
      - --unattended
  tags: unbound